/* Automatically generated by 'scripts/gen-entry.js' */

import Table from './table/index.js';

const components = [
  Table,
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  install,
  Table
};
